/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Vamshi
 */

public class rolls extends javax.swing.JFrame {
    public static String branch=hodDash.branch;
    public String table=branch+"rolls";
public ArrayList<user> userList(){
    ArrayList<user> userList=new ArrayList<>();
      try {
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/vamshi","root","9035");
    String query1="select * from "+table+" order by sno";
    Statement st=conn.createStatement();
    ResultSet rs=st.executeQuery(query1);
    user us;
    while(rs.next()){
        us=new user(rs.getInt("sno"),rs.getString("name"),rs.getString("htno"),rs.getString("gpa"),rs.getString("gender"));
        userList.add(us);
    }
      }catch (Exception ex) {
            System.out.println(ex);
        } 
      return userList;
}

public void showuser() throws ClassNotFoundException, SQLException{
    ArrayList<user> list=userList();
    DefaultTableModel model=(DefaultTableModel)tb1.getModel();
    Object[] row = new Object[5];
    for(int i=0;i<list.size();i++){
        row[0]=list.get(i).getname();
        row[1]=list.get(i).gethtno();
        row[2]=list.get(i).getgpa();
        row[3]=list.get(i).getgender();
        model.addRow(row);
    }
  try {
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/vamshi","root","9035");
    PreparedStatement ps=conn.prepareStatement("select htno from "+table);
    ResultSet rs=ps.executeQuery();
    while(rs.next()){
        cb1.addItem(rs.getString(1));
    }
  }catch (SQLException ex) {
            Logger.getLogger(enrolls.class.getName()).log(Level.SEVERE, null, ex);
        }
  
}
    /**
     * Creates new form enrolls
     */
    public rolls() throws ClassNotFoundException, SQLException {
        initComponents();
        showuser();
        lb1.setText(branch+" enroll requests");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        cb1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tb1.setBackground(new java.awt.Color(255, 153, 153));
        tb1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "name", "ht no", "GPA", "Gender"
            }
        ));
        tb1.setColumnSelectionAllowed(true);
        tb1.setRowHeight(20);
        tb1.setRowSelectionAllowed(false);
        tb1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);
        tb1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        cb1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select>" }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("ADMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lb1.setBackground(new java.awt.Color(51, 51, 255));
        lb1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void formMouseClicked(java.awt.event.MouseEvent evt) {                                  
        // TODO add your handling code here:
    }                                 

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {                                 

    }                                

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {                                    
        
    }                                   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        replace();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      String v2=(String) cb1.getSelectedItem();
        if(v2=="<select>"){
            JOptionPane.showMessageDialog(rootPane, "SELECT A STUDENT TO ADMIT");
        }
        else{
            try {
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/vamshi","root","9035");
    PreparedStatement ps=conn.prepareStatement("delete from "+table+" where htno=?");
    ps.setString(1,v2);
    ps.executeUpdate();
                this.dispose();
            new rolls().setVisible(true);
  }catch (SQLException ex) {
            Logger.getLogger(enrolls.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(enrolls.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }                                        
public void replace() {
          String v2=(String) cb1.getSelectedItem();
        if(v2=="<select>"){
            JOptionPane.showMessageDialog(rootPane, "SELECT A STUDENT TO ADMIT");
        }
        else{
            try {
     Class.forName("com.mysql.jdbc.Driver");
    Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/vamshi","root","9035");
    PreparedStatement ps=conn.prepareStatement("delete from "+table+" where htno=?");
    ps.setString(1,v2);
    ps.executeUpdate();
    ps=conn.prepareStatement("delete from jits where htno=?");
    ps.setString(1,v2);
    ps.executeUpdate();
    JOptionPane.showMessageDialog(rootPane, v2+" deleted from database");
    this.dispose();
    new rolls().setVisible(true);
  }catch (SQLException ex) {
            Logger.getLogger(enrolls.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(enrolls.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enrolls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new enrolls().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(enrolls.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(enrolls.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTable tb1;
    // End of variables declaration                   

    
}
